### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by liskin** [IxpertaSolutions/freer-effects#4]
https://github.com/fpco/stackage/pull/2239#issuecomment-275864214

**Comment by trskop** [comment]
What about:

* `even-freer`
* `freer-effects`

**Comment by liskin** [comment]
Maťo and I also thought about `freeer`, but `freer-effects` better communicates the fact that it's about effects. Also, `synopsis: Implementation of the Freer Monad` should probably be improved.

**Comment by trskop** [comment]
I've made an informal poll in our office, and it seems that people are OK with `freer-effects`. As you have already noticed, it makes explicit mention of effects, which is always good way of conveying what the package is for.

+1 for updating Synopsis field.

**Comment by trskop** [comment]
Renaming to `freer-effects` is done, which includes the repository.

This was decided today on a session where @liskin @Siprj @xkollar and I were present.
